### ISSUE TITLE
Connect to a node already connected to

### ISSUE THREAD

**Issue by alrevuelta** [macsnoeren/python-p2p-network#24]
I was wondering why a node can't connect to a node that is already connected to the former. See [this line](https://github.com/macsnoeren/python-p2p-network/blob/development/p2pnetwork/node.py#L169). Lets say that `nodeA` has an outbound connection to `nodeB`. Why can't `nodeB` have an outbound connection to `nodeA`?

Perhaps I don't fully understand how connections work. Lets say that we have the following connections: `nodeA`->`nodeB`->`nodeC`, where `->` denotes a connection, being the node on the left the outbound one and the right the inbound. Summarised as:
* `nodeA` has an outbound connection to `nodeB`
* `nodeB` has an inbound connection to `nodeA`
* `nodeB` has an outbound connection to `nodeC`
* `nodeC` has an inbound connection to `nodeB`

If in the previous setup a `nodeB` calls `send_to_nodes`, will it reach `nodeA`?

Thanks!

**Comment by macsnoeren** [comment]
Within Blockchain you form a network between the nodes. When nodeA and nodeB are connected somehow (inbound or outbound), they already have a connection together within this network. This connection is bi-directional. Both nodes are able to start communication with each other. So, there is no need to make on TCP/IP level two connections. Another aspect is, when allowing two TCP/IP connections between the same nodes, it makes things more complex than needed. Thus, for the blockchain network you just need a connection between the two. How this has been established is not relevant.

**Comment by macsnoeren** [comment]
Now your question "If in the previous setup a nodeB calls send_to_nodes, will it reach nodeA?". In this case ... no ... but you can implement this. It is application specific. This Python library tends to be a framework in which you can implement peer-to-peer decentralized applications. In your example, you can implement that nodeB relays the message to nodeA. In fact, within peer-to-peer decentralized application, this is very common to have. For example, you could send a discovery message in order to see how big the network is. If a node gets this discovery message, it should relay it further into the network. To prevent circulation of messages like these, you need to do some administration.

**Comment by macsnoeren** [comment]
I assume your question has been answered ;).
